name: forecast_accuracy_app
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - xarray
  - pyarrow
  - requests
  - streamlit
  - altair
  - sqlalchemy
  - duckdb
  - geopandas
  - pyproj
  - shapely
  - rasterio
  - cfgrib
  - python-dateutil
  - pytest
  - pip:
      - python-dotenv
      - duckdb-engine
      - psycopg[binary]
      - folium
      - streamlit-folium
