[app]
title = "Forecast Accuracy App"
default_lat = 35.028961
default_lon = -120.496292
default_state = "CA"
default_variables = ["TMAX", "TMIN", "PRCP"]
default_lead_hours = [0, 24, 48, 72, 96, 120, 144, 168]

[data]
cache_dir = "data"
forecast_dir = "data/forecasts"
obs_dir = "data/obs"
scores_dir = "data/scores"
archive_dir = "data/ndfd"

[api]
nws_base_url = "https://api.weather.gov/gridpoints"
nws_timeout = 30
nws_retries = 3
ncei_base_url = "https://www.ncdc.noaa.gov/cdo-web/api/v2"
ncei_timeout = 30
ncei_retries = 3

[forecast_archive]
base_url = "https://nomads.ncep.noaa.gov/pub/data/nccf/com/ndgd/prod"
sector = "conus"
product_files = { TMAX = "ds.max_temp.bin", TMIN = "ds.min_temp.bin", PRCP = "ds.qpf.bin" }
grid = "ndfd"
